### ISSUE TITLE
Intelligent swapping of strategies

### ISSUE THREAD

**Issue by cgbriggs99** [Einsums/Einsums#32]
We want to develop a way to swap intelligently between GPU and CPU based strategies.

**Comment by cgbriggs99** [comment]
I've run some tests on matrix multiplication. Here are my results.
![Graph of cpu vs gpu](https://github.com/cgbriggs99/einsums/blob/hip-tensors/images/fig1.png)
This is a graph of two different GPU strategies vs MKL. The crossover point between the copy strategy and MKL is around 170 rows. As for the mapped strategy, the first cross-over point is at 41 rows, with subsequent cross-overs every 64 added rows.

**Comment by cgbriggs99** [comment]
![First graph of the two different strategies](https://github.com/cgbriggs99/einsums/blob/hip-tensors/images/fig2.png)
![Graph of the two different strategies](https://github.com/cgbriggs99/einsums/blob/hip-tensors/images/fig4.png)
As for the different strategies, memory mapping seems to work better for even-numbered dimensions from 174 rows to 192 rows, where it becomes consistently better until 220 rows. Memory mapping is then better from 256 rows to 268 rows. After this, copying to vRAM is always better.

**Comment by cgbriggs99** [comment]
I tested two different graphics-accelerated BLAS libraries: hipBLAS and rocBLAS. The difference between the two was negligible.
![Comparison between HIP and ROCm](https://github.com/cgbriggs99/einsums/blob/hip-tensors/images/fig3.png)

**Comment by cgbriggs99** [comment]
I hope some of these results can help with some discussion about dynamically selecting compute strategies.

**Comment by cgbriggs99** [comment]
I've put the code I used to generate the graphs in https://github.com/cgbriggs99/einsums/tree/main/timing/comparisons for those interested.

**Comment by cgbriggs99** [comment]
One thing to note about these results is that these were treated as if they were in isolation. In reality, the GPU algorithms are asynchronous.

**Comment by jturney** [comment]
This is super nice! Thanks for doing it.

Let's figure out a strategy and code structure for swapping backends at runtime.

**Comment by cgbriggs99** [comment]
A simple suggestion for the logic could be if the GPU is in use and the operation is small, use a CPU algorithm. If the operation is larger, then copy the memory into vRAM and use the GPU when it is available. If the operation is too large to be held in vRAM, map RAM to the GPU. If the memory is massive and stored on the disk, use a CPU algorithm.

**Comment by cgbriggs99** [comment]
How about this. I basically "stole" the gang of four's structure for a template method and a strategy working together.
![UML diagram](https://github.com/cgbriggs99/einsums/blob/main/images/class%20diagram.png?raw=true)
