### ISSUE TITLE
CMake Tests

### ISSUE THREAD

**Issue by jturney** [Einsums/Einsums#49]
If you have einsums installed in a conda environment and also build ensues from source chances are the wrong library will be used. When running the test suite manually or through CTest, most likely, the shared library that will be used is the one found in your condo environment. Look into using `LD_PRELOAD` in CMake so that CTest will use the correct version.

**Comment by loriab** [comment]
fwiw, I think I'd consider it developer error to have an installed and a src target library available. You could link a static einsums into test-all to really avoid it, I guess.

**Comment by jturney** [comment]
Good point.
